version: "3.8"

services:
  # ---------------------------
  # RabbitMQ
  # ---------------------------
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    networks:
      - ecommerce-network
    expose:
      - "5672"
      - "15672"

  # ---------------------------
  # Gateway (REST)
  # ---------------------------
  gateway:
    build: ./gateway
    container_name: gateway
    command: npm run dev
    restart: always
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3000"

  # ---------------------------
  # GraphQL Gateway
  # ---------------------------
  graphql-gateway:
    build: ./graphql-gateway
    container_name: graphql-gateway
    command: npm run dev
    restart: always
    environment:
      - PORT=4000
      - USER_SERVICE_URL=http://user-service:3001/api/v1
      - PRODUCT_SERVICE_URL=http://product-service:3002/api/v1
      - ORDER_SERVICE_URL=http://order-service:3003/api/v1
      - SELLER_SERVICE_URL=http://seller-service:3007/api/v1
      - INVENTORY_SERVICE_URL=http://inventory-service:3010/api/v1
      - FULFILLMENT_SERVICE_URL=http://fulfillment-service:3008/api/v1
      - SUPPORT_SERVICE_URL=http://support-service:3009/api/v1
      - CART_SERVICE_URL=http://cart-service:3005/api/v1
      - PAYMENT_SERVICE_URL=http://payment-service:3004/api/v1
      - NOTIFICATION_SERVICE_URL=http://notification-service:3006/api/v1
      - MARKETING_SERVICE_URL=http://marketing-service:3011/api/v1
    depends_on:
      - user-service
      - product-service
      - order-service
      - seller-service
      - inventory-service
      - fulfillment-service
      - support-service
      - cart-service
      - payment-service
      - notification-service
      - marketing-service
    networks:
      - ecommerce-network
    expose:
      - "4000"

  # ---------------------------
  # Microservices
  # ---------------------------

  user-service:
    build: ./services/user-service
    command: npm run dev
    restart: always
    environment:
      - PORT=3001
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3001"

  product-service:
    build: ./services/product-service
    command: npm run dev
    restart: always
    environment:
      - PORT=3002
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3002"

  order-service:
    build: ./services/order-service
    command: npm run dev
    restart: always
    environment:
      - PORT=3003
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3003"

  payment-service:
    build: ./services/payment-service
    command: npm run dev
    restart: always
    environment:
      - PORT=3004
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3004"

  cart-service:
    build: ./services/cart-service
    command: npm run dev
    restart: always
    environment:
      - PORT=3005
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3005"

  notification-service:
    build: ./services/notification-service
    command: npm run dev
    restart: always
    environment:
      - PORT=3006
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3006"

  seller-service:
    build: ./services/seller-service
    command: npm run dev
    restart: always
    environment:
      - PORT=3007
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3007"

  fulfillment-service:
    build: ./services/fulfillment-service
    command: npm run dev
    restart: always
    environment:
      - PORT=3008
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3008"

  support-service:
    build: ./services/support-service
    command: npm run dev
    restart: always
    environment:
      - PORT=3009
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3009"

  inventory-service:
    build: ./services/inventory-service
    command: npm run dev
    restart: always
    environment:
      - PORT=3010
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3010"
  
  marketing-service:
    build: ./services/marketing-service
    command: npm run dev
    restart: always
    environment:
      - PORT=3011
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - ecommerce-network
    expose:
      - "3011"

  # ---------------------------
  # NGINX Reverse Proxy
  # ---------------------------

  nginx:
   image: nginx:alpine
   container_name: nginx
   restart: always
   depends_on:
    - gateway
    - graphql-gateway
   ports:
    - "80:80"
    - "443:443"
   volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
   networks:
    - ecommerce-network

    
  certbot:
   image: certbot/certbot
   volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot


# ---------------------------
# Network
# ---------------------------
networks:
  ecommerce-network:
    driver: bridge
